  version: '3.8'

  services:
    sinapsis-dev-mysql-service:
      container_name: sinapsis-dev-mysql-container
      build: .
      restart: always
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: FWntl7yyyDX6Th5hwv2x0BKT
        MYSQL_USER: backend_database_user
        MYSQL_PASSWORD: SZw2iZr7YTZ73d79
        MYSQL_DATABASE: product_db
      volumes:
        - ./mysql_data:/var/lib/mysql
  
    sinapsis-dev-phpmyadmin-service:
      container_name: sinapsis-dev-phpmyadmin-container
      image: phpmyadmin
      restart: always
      ports:
      - 8080:80
      environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=sinapsis-dev-mysql-service
      - PMA_USER=backend_database_user
      - PMA_PASSWORD=SZw2iZr7YTZ73d79
        
